### ISSUE TITLE
Bad Responsiveness

### ISSUE THREAD

**Issue by DineshDhanji** [BurhanCantCode/DevDay-Page#2]
If the content gets out of the screen, then the user can not scroll the page. 

![image](https://github.com/BurhanCantCode/DevDay-Page/assets/56204876/aeb50dc2-eda8-4619-be91-69cf407b5068)

At the screen resolution of 4K, the background text overlaps.

![image](https://github.com/BurhanCantCode/DevDay-Page/assets/56204876/47ff6646-d04d-49a0-bbf5-f1b5878df41f)

**Comment by burhankhatri** [comment]
![os](https://github.com/BurhanCantCode/DevDay-Page/assets/144617735/52dddf94-7358-456b-86e4-935258655624)

**Comment by DineshDhanji** [comment]
Noice
